spring:
  application:
    name: ai-assistant
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
        enabled: true
    vectorstore:
      pgvector:
        initialize-schema: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    org:
      apache:
        pdfbox:
          pdmodel:
            font:
              FileSystemFontProvider: ERROR
      springframework:
        security: DEBUG


keycloak:
  realm: ${KC_REALM}
  auth-server-url: ${KC_AUTH_URL}
  ssl-required: external
  resource: ${KC_CLIENT}
  credentials:
    secret: ${KC_SECRET}
  use-resource-role-mappings: true
  autodetect-bearer-only: true

keycloak-token:
  url: ${KC_TOKEN_URL}


master:
  user:
    username: ${KC_ADMIN_USER}
    password: ${KC_ADMIN_PASSWORD}
  realm: master
  client: admin-cli


server:
  port: 1010
